export default [
  {
    "id": "1",
    "tipoAtivo": "IMOVEL",
    "tipocompra": "DINHEIRO",
    "descricao": "Casa Temporaria",
    "vendido": false,
    "nomeProprietario": "Renato Cristiano F F",
    "donoReal": "Renato Cristiano F F",
    "pais": "BRASIL",
    "uf": "BA",
    "cidade": "Camaçari",
    "codPostal": "42801260",
    "endereco": "Rua xxx dawdawdwa",
    "nr": "19",
    "complemento": null,
    "bairro": "Centro",
    "idUsuario": 1,
    "nrimovel": null,
    "renavam": null,
    "placa": null,
    "anoModelo": null,
    "anoFab": null,
    "exercicio": null,
    "marca": null,
    "modelo": null,
    "versao": null,
    "chassi": null,
    "cor": null,
    "combustivel": null,
    "nrMotor": null,
    "cilindrada": null,
    "nrIncriscao": null,
    "dataInscricao": null,
    "validade": null,
    "nome": null,
    "propulsao": null,
    "tipoEmbarcacao": null,
    "potencia": null,
    "nrMotor1": null,
    "fabricante1": null,
    "nrMotor2": null,
    "fabricante2": null,
    "nrMotor3": null,
    "fabricante3": null,
    "areaNavegacao": null,
    "atividade": null,
    "nrTripulante": null,
    "nrPassageiro": null,
    "construtor": null,
    "anoConstrucao": null,
    "cumprimento": null,
    "tipoCasco": null,
    "nrSerieCasco": null,
    "createdAt": "2021-04-23T21:19:18.533Z",
    "updatedAt": "2021-04-23T21:19:18.533Z"
  },
  {
    "id": "2",
    "tipoAtivo": "VEICULO",
    "tipocompra": "DINHEIRO",
    "descricao": "Primeiro Carro",
    "vendido": false,
    "nomeProprietario": "Renato Cristiano F F",
    "donoReal": "Renato Cristiano F F",
    "pais": "BRASIL",
    "uf": "BA",
    "cidade": "Camaçari",
    "codPostal": "42801260",
    "endereco": "Rua xxx dawdawdwa",
    "nr": "19",
    "complemento": null,
    "bairro": "Centro",
    "idUsuario": 1,
    "nrimovel": null,
    "renavam": null,
    "placa": null,
    "anoModelo": null,
    "anoFab": null,
    "exercicio": null,
    "marca": null,
    "modelo": null,
    "versao": null,
    "chassi": null,
    "cor": null,
    "combustivel": null,
    "nrMotor": null,
    "cilindrada": null,
    "nrIncriscao": null,
    "dataInscricao": null,
    "validade": null,
    "nome": null,
    "propulsao": null,
    "tipoEmbarcacao": null,
    "potencia": null,
    "nrMotor1": null,
    "fabricante1": null,
    "nrMotor2": null,
    "fabricante2": null,
    "nrMotor3": null,
    "fabricante3": null,
    "areaNavegacao": null,
    "atividade": null,
    "nrTripulante": null,
    "nrPassageiro": null,
    "construtor": null,
    "anoConstrucao": null,
    "cumprimento": null,
    "tipoCasco": null,
    "nrSerieCasco": null,
    "createdAt": "2021-04-23T21:20:18.533Z",
    "updatedAt": "2021-04-23T21:20:18.533Z"
  },
  {
    "id": "3",
    "tipoAtivo": "EMBARCACAO",
    "tipocompra": "DINHEIRO",
    "descricao": "Primeiro Jet",
    "vendido": false,
    "nomeProprietario": "Renato Cristiano F F",
    "donoReal": "Renato Cristiano F F",
    "pais": "BRASIL",
    "uf": "BA",
    "cidade": "Camaçari",
    "codPostal": "42801260",
    "endereco": "Rua xxx dawdawdwa",
    "nr": "19",
    "complemento": null,
    "bairro": "Centro",
    "idUsuario": 1,
    "nrimovel": null,
    "renavam": null,
    "placa": null,
    "anoModelo": null,
    "anoFab": null,
    "exercicio": null,
    "marca": null,
    "modelo": null,
    "versao": null,
    "chassi": null,
    "cor": null,
    "combustivel": null,
    "nrMotor": null,
    "cilindrada": null,
    "nrIncriscao": null,
    "dataInscricao": null,
    "validade": null,
    "nome": null,
    "propulsao": null,
    "tipoEmbarcacao": null,
    "potencia": null,
    "nrMotor1": null,
    "fabricante1": null,
    "nrMotor2": null,
    "fabricante2": null,
    "nrMotor3": null,
    "fabricante3": null,
    "areaNavegacao": null,
    "atividade": null,
    "nrTripulante": null,
    "nrPassageiro": null,
    "construtor": null,
    "anoConstrucao": null,
    "cumprimento": null,
    "tipoCasco": null,
    "nrSerieCasco": null,
    "createdAt": "2021-04-24T21:19:18.533Z",
    "updatedAt": "2021-04-24T21:19:18.533Z"
  },
  {
    "id": "4",
    "tipoAtivo": "EMBARCACAO",
    "tipocompra": "DINHEIRO",
    "descricao": "Primeiro Jet",
    "vendido": false,
    "nomeProprietario": "Renato Cristiano F F",
    "donoReal": "Renato Cristiano F F",
    "pais": "BRASIL",
    "uf": "BA",
    "cidade": "Camaçari",
    "codPostal": "42801260",
    "endereco": "Rua xxx dawdawdwa",
    "nr": "19",
    "complemento": null,
    "bairro": "Centro",
    "idUsuario": 1,
    "nrimovel": null,
    "renavam": null,
    "placa": null,
    "anoModelo": null,
    "anoFab": null,
    "exercicio": null,
    "marca": null,
    "modelo": null,
    "versao": null,
    "chassi": null,
    "cor": null,
    "combustivel": null,
    "nrMotor": null,
    "cilindrada": null,
    "nrIncriscao": null,
    "dataInscricao": null,
    "validade": null,
    "nome": null,
    "propulsao": null,
    "tipoEmbarcacao": null,
    "potencia": null,
    "nrMotor1": null,
    "fabricante1": null,
    "nrMotor2": null,
    "fabricante2": null,
    "nrMotor3": null,
    "fabricante3": null,
    "areaNavegacao": null,
    "atividade": null,
    "nrTripulante": null,
    "nrPassageiro": null,
    "construtor": null,
    "anoConstrucao": null,
    "cumprimento": null,
    "tipoCasco": null,
    "nrSerieCasco": null,
    "createdAt": "2021-04-24T21:19:18.533Z",
    "updatedAt": "2021-04-24T21:19:18.533Z"
  },
];